import { CaseData } from '@/components/shared/CaseDetailsView';

export const fallbackIncident = (id: string): CaseData => ({
  id: id || 'PSIRP-2025-0025',
  title: 'High-Value Package Theft',
  status: 'In Review',
  severity: 'High',
  description: 'A high-value package containing electronic goods was reported missing from the KL Distribution Center during the morning shift. The package was last scanned at 08:45 AM and could not be located during the 10:00 AM audit.',
  incidentDate: '2025-01-15',
  incidentTime: '08:45',
  incidentLocation: 'Lot 5, Jalan Teknologi, Taman Sains Selangor, Shah Alam',
  dateReported: '2025-01-15 10:30',
  branchName: 'KL Main Distribution Center',
  address: 'Lot 5, Jalan Teknologi, Taman Sains Selangor',
  state: 'Selangor',
  postalCode: '47810',
  companyName: 'Pos Malaysia Berhad',
  registeredAddress: 'Dayabumi Complex, Jalan Sultan Hishamuddin, 50670 Kuala Lumpur',
  reporterName: 'Ahmad bin Ibrahim',
  reporterDesignation: 'Security Manager',
  reporterEmail: 'ahmad.ibrahim@posmalaysia.com.my',
  alternativeEmail: 'ahmad.sec@gmail.com',
  reporterPhone: '+60 12-345 6789',
  additionalPhone: '+60 17-888 9999',
  faxNumber: '+60 3-2222 3333',
  leaEscalation: 'No',
  systemServiceAffected: 'Parcel Tracking System',
  observedImpact: 'Financial Impact',
  primaryIncidentType: 'Theft or loss of postal items',
  staffDetected: { name: 'Ali bin Hassan', designation: 'Warehouse Supervisor', contactNumber: '+60 13-456 7890', email: 'ali.hassan@posmalaysia.com.my' },
  senderInfo: { name: 'TechCo Sdn Bhd', address: '12 Jalan Tech, KL', stateCountry: 'Kuala Lumpur, Malaysia', contact: '+60123456789' },
  recipientInfo: { name: 'Ahmad bin Ibrahim', address: '45 Jalan Mawar, Shah Alam', stateCountry: 'Selangor, Malaysia', contact: '+60198765432' },
  trackingNumber: 'EC20250115-12345',
  packageDeclaration: 'Sample Electronic Device - Prohibited Lithium Battery',
  packageWeight: '1.2',
  prohibitedItemType: 'Lithium Batteries',
  otherRelatedInfo: 'The item was flagged during x-ray screening at the departure gate.',
  linkDescription: 'Detailed screening report and x-ray images: https://storage.pos.my/evidence/ABXX0020-xray',
  immediateActions: 'Parcel isolated in a secure cabinet, local authorities notified, and sender is being contacted for clarification.',
  incidentContained: 'Yes',
  incidentControlStatus: 'Contained',
  reportedToAuthority: 'Yes',
  authorityAgency: 'PDRM',
  authorityReference: 'RPT-2025-KL-0045',
  authorityDetails: 'PDRM — RPT-2025-KL-0045',
  parcelHandedOver: 'Yes',
  assistanceRequested: ['Investigation Support', 'Security Audit'],
  documents: [
    { name: 'X-Ray_Screening_B102.png', size: '1.8 MB', uploadedBy: 'Ahmad bin Ibrahim', uploadDate: '2025-01-15 10:25' },
    { name: 'Incident_Report_Internal.pdf', size: '1.1 MB', uploadedBy: 'Ahmad bin Ibrahim', uploadDate: '2025-01-15 10:28' },
  ],
  declarationAgreed: true,
  declarationDate: '2025-01-15',
});
